term.setBackgroundColor(colors.blue)
term.setTextColor(colors.white)
term.clear()
term.setCursorPos(2, 2)
print(":(")
term.setCursorPos(2, 4)
print("Your computer needs to restart.")
term.setCursorPos(2, 6)
print("ERR_NOT_IMPLEMENTED")
sleep(5)
term.setBackgroundColor(colors.black)
term.clear()
sleep(1)
os.reboot()
